/* Generated by tools/awl_to_c.py from filter.awl - do not edit, edit the .awl */
#include "plc.h"

const char *const plc_program_file = "filter.awl";

void plc_main(void)
{
    /* Network 1 */
    /* Idle State 0 */
    PLC_AT(1, 6, "LD SM0.1"); LD(B('X', 0, 1));
    PLC_AT(1, 7, "O I0.2"); O(B('I', 0, 2));
    PLC_AT(1, 8, "OB= VB202, 14"); OB(RB('V', 202), ==, 14);
    PLC_AT(1, 9, "O Q1.1"); O(B('Q', 1, 1));
    PLC_AT(1, 10, "LDB= VB202, 18"); LDB(RB('V', 202), ==, 18);
    PLC_AT(1, 11, "AN Q0.6"); AN(B('Q', 0, 6));
    PLC_AT(1, 12, "OLD"); OLD();
    PLC_AT(1, 13, "MOVB 0, VB202"); MOVB(0, 202);

    /* Network 2 */
    /* State 1 Regen open then delay after start pulse */

    /* Network 3 */
    /* Exit State 1 to State 2. Regen valve timer complete. Move to State 2 turn pump on */
    PLC_AT(3, 18, "LDN I0.2"); LDN(B('I', 0, 2));
    PLC_AT(3, 19, "AN V204.0"); AN(B('V', 204, 0));
    PLC_AT(3, 20, "AN V210.0"); AN(B('V', 210, 0));
    PLC_AT(3, 21, "LPS"); LPS();
    PLC_AT(3, 22, "LDB= VB202, 0"); LDB(RB('V', 202), ==, 0);
    PLC_AT(3, 23, "A V230.0"); A(B('V', 230, 0));
    PLC_AT(3, 24, "OB= VB202, 19"); OB(RB('V', 202), ==, 19);
    PLC_AT(3, 25, "ALD"); ALD();
    PLC_AT(3, 26, "MOVB 1, VB202"); MOVB(1, 202);
    PLC_AT(3, 27, "LPP"); LPP();
    PLC_AT(3, 28, "LPS"); LPS();
    PLC_AT(3, 29, "A T37"); A(TB(37));
    PLC_AT(3, 30, "MOVB 2, VB202"); MOVB(2, 202);
    PLC_AT(3, 31, "LRD"); LRD();
    PLC_AT(3, 32, "A T38"); A(TB(38));
    PLC_AT(3, 33, "MOVB 3, VB202"); MOVB(3, 202);
    PLC_AT(3, 34, "LRD"); LRD();
    PLC_AT(3, 35, "A T39"); A(TB(39));
    PLC_AT(3, 36, "MOVB 4, VB202"); MOVB(4, 202);
    PLC_AT(3, 37, "LRD"); LRD();
    PLC_AT(3, 38, "A T40"); A(TB(40));
    PLC_AT(3, 39, "MOVB 5, VB202"); MOVB(5, 202);
    PLC_AT(3, 40, "LRD"); LRD();
    PLC_AT(3, 41, "A T41"); A(TB(41));
    PLC_AT(3, 42, "MOVB 6, VB202"); MOVB(6, 202);
    PLC_AT(3, 43, "LPP"); LPP();
    PLC_AT(3, 44, "AB= VB202, 0"); AB(RB('V', 202), ==, 0);
    PLC_AT(3, 45, "A Q0.4"); A(B('Q', 0, 4));
    PLC_AT(3, 46, "MOVB 15, VB202"); MOVB(15, 202);

    /* Network 4 */
    /* State 1 Transition logic, Regen Valve Timer delay to Pump on (preset VW300, set by HMI) */
    PLC_AT(4, 49, "LDB= VB202, 1"); LDB(RB('V', 202), ==, 1);
    PLC_AT(4, 50, "TON T37, VW300"); TON(37, RW('V', 300));

    /* Network 5 */
    /* State 2 Transition logic, Motor on then delay to next state, regen filter (preset VW302) */
    PLC_AT(5, 53, "LDB= VB202, 2"); LDB(RB('V', 202), ==, 2);
    PLC_AT(5, 54, "TON T38, VW302"); TON(38, RW('V', 302));

    /* Network 6 */
    /* State 3 Transition logic, Coat media on to filter tubes (preset VW304) */
    PLC_AT(6, 57, "LDB= VB202, 3"); LDB(RB('V', 202), ==, 3);
    PLC_AT(6, 58, "TON T39, VW304"); TON(39, RW('V', 304));

    /* Network 7 */
    /* State 4 Transition logic, Effluent valve delay before regen valve closed (preset VW306) */
    PLC_AT(7, 61, "LDB= VB202, 4"); LDB(RB('V', 202), ==, 4);
    PLC_AT(7, 62, "TON T40, VW306"); TON(40, RW('V', 306));

    /* Network 8 */
    /* State 5 Transition logic, Regen Valve Closed Delay time (preset VW308) */
    PLC_AT(8, 65, "LDB= VB202, 5"); LDB(RB('V', 202), ==, 5);
    PLC_AT(8, 66, "TON T41, VW308"); TON(41, RW('V', 308));

    /* Network 9 */

    /* Network 10 */

    /* Network 11 */

    /* Network 12 */
    PLC_AT(12, 71, "LD I1.2"); LD(B('I', 1, 2));
    PLC_AT(12, 72, "LD Q0.4"); LD(B('Q', 0, 4));
    PLC_AT(12, 73, "AB<> VB202, 0"); AB(RB('V', 202), !=, 0);
    PLC_AT(12, 74, "OLD"); OLD();
    PLC_AT(12, 75, "EU"); EU(0);
    PLC_AT(12, 76, "= V204.1"); OUT('V', 204, 1);

    /* Network 13 */
    /* Cancel run, once user stop pressed stay there until idle state is achieved */
    PLC_AT(13, 79, "LD V204.1"); LD(B('V', 204, 1));
    PLC_AT(13, 80, "O V204.0"); O(B('V', 204, 0));
    PLC_AT(13, 81, "AB<> VB202, 0"); AB(RB('V', 202), !=, 0);
    PLC_AT(13, 82, "AB< VB202, 15"); AB(RB('V', 202), <, 15);
    PLC_AT(13, 83, "= V204.0"); OUT('V', 204, 0);

    /* Network 14 */
    /* User Stop pulse found, change to correct exit state based on current state */
    PLC_AT(14, 86, "LDN I0.2"); LDN(B('I', 0, 2));
    PLC_AT(14, 87, "LD V204.1"); LD(B('V', 204, 1));
    PLC_AT(14, 88, "O Q0.4"); O(B('Q', 0, 4));
    PLC_AT(14, 89, "ALD"); ALD();
    PLC_AT(14, 90, "LPS"); LPS();
    PLC_AT(14, 91, "LDB= VB202, 6"); LDB(RB('V', 202), ==, 6);
    PLC_AT(14, 92, "OB= VB202, 5"); OB(RB('V', 202), ==, 5);
    PLC_AT(14, 93, "ALD"); ALD();
    PLC_AT(14, 94, "MOVB 10, VB202"); MOVB(10, 202);
    PLC_AT(14, 95, "LRD"); LRD();
    PLC_AT(14, 96, "LPS"); LPS();
    PLC_AT(14, 97, "AB= VB202, 4"); AB(RB('V', 202), ==, 4);
    PLC_AT(14, 98, "MOVB 11, VB202"); MOVB(11, 202);
    PLC_AT(14, 99, "LPP"); LPP();
    PLC_AT(14, 100, "AB= VB202, 3"); AB(RB('V', 202), ==, 3);
    PLC_AT(14, 101, "MOVB 12, VB202"); MOVB(12, 202);
    PLC_AT(14, 102, "LPP"); LPP();
    PLC_AT(14, 103, "LDB= VB202, 2"); LDB(RB('V', 202), ==, 2);
    PLC_AT(14, 104, "OB= VB202, 1"); OB(RB('V', 202), ==, 1);
    PLC_AT(14, 105, "ALD"); ALD();
    PLC_AT(14, 106, "MOVB 13, VB202"); MOVB(13, 202);

    /* Network 15 */
    /* Stop sequence: move to the next stop step when its timer is done (10 -> 11 -> 12 -> 13 -> 14) */
    PLC_AT(15, 109, "LDN I0.2"); LDN(B('I', 0, 2));
    PLC_AT(15, 110, "A V204.0"); A(B('V', 204, 0));
    PLC_AT(15, 111, "LPS"); LPS();
    PLC_AT(15, 112, "A T42"); A(TB(42));
    PLC_AT(15, 113, "MOVB 11, VB202"); MOVB(11, 202);
    PLC_AT(15, 114, "LRD"); LRD();
    PLC_AT(15, 115, "A T43"); A(TB(43));
    PLC_AT(15, 116, "MOVB 12, VB202"); MOVB(12, 202);
    PLC_AT(15, 117, "LRD"); LRD();
    PLC_AT(15, 118, "A T44"); A(TB(44));
    PLC_AT(15, 119, "MOVB 13, VB202"); MOVB(13, 202);
    PLC_AT(15, 120, "LPP"); LPP();
    PLC_AT(15, 121, "A T45"); A(TB(45));
    PLC_AT(15, 122, "MOVB 14, VB202"); MOVB(14, 202);

    /* Network 16 */
    /* Stop step 10: regen valve open, delay before the effluent valve closes (preset VW310) */
    PLC_AT(16, 125, "LDB= VB202, 10"); LDB(RB('V', 202), ==, 10);
    PLC_AT(16, 126, "TON T42, VW310"); TON(42, RW('V', 310));

    /* Network 17 */
    /* Stop step 11: effluent valve closed, delay before the pump stops (preset VW312) */
    PLC_AT(17, 129, "LDB= VB202, 11"); LDB(RB('V', 202), ==, 11);
    PLC_AT(17, 130, "TON T43, VW312"); TON(43, RW('V', 312));

    /* Network 18 */
    /* Stop step 12: pump off, delay before the regen valve closes (preset VW314) */
    PLC_AT(18, 133, "LDB= VB202, 12"); LDB(RB('V', 202), ==, 12);
    PLC_AT(18, 134, "TON T44, VW314"); TON(44, RW('V', 314));

    /* Network 19 */
    /* Stop step 13: regen valve closed, delay before idle (preset VW316) */
    PLC_AT(19, 137, "LDB= VB202, 13"); LDB(RB('V', 202), ==, 13);
    PLC_AT(19, 138, "TON T45, VW316"); TON(45, RW('V', 316));

    /* Network 20 */

    /* Network 21 */

    /* Network 22 */
    /* End of state machine sequences */

    /* Network 23 */

    /* Network 24 */

    /* Network 25 */

    /* Network 26 */
    PLC_AT(26, 148, "LD I0.0"); LD(B('I', 0, 0));
    PLC_AT(26, 149, "EU"); EU(1);
    PLC_AT(26, 150, "= V230.0"); OUT('V', 230, 0);

    /* Network 27 */
    PLC_AT(27, 152, "LDN I1.0"); LDN(B('I', 1, 0));
    PLC_AT(27, 153, "EU"); EU(2);
    PLC_AT(27, 154, "= V230.1"); OUT('V', 230, 1);

    /* Network 28 */
    /* Pump: on in states 2-6 and 10-11, or by the HMI (V250.0) in idle (Drain / Rinse) */
    PLC_AT(28, 157, "LDB= VB202, 2"); LDB(RB('V', 202), ==, 2);
    PLC_AT(28, 158, "O Q0.0"); O(B('Q', 0, 0));
    PLC_AT(28, 159, "AN V210.0"); AN(B('V', 210, 0));
    PLC_AT(28, 160, "AB<> VB202, 0"); AB(RB('V', 202), !=, 0);
    PLC_AT(28, 161, "AB<> VB202, 12"); AB(RB('V', 202), !=, 12);
    PLC_AT(28, 162, "LD V250.0"); LD(B('V', 250, 0));
    PLC_AT(28, 163, "AB= VB202, 0"); AB(RB('V', 202), ==, 0);
    PLC_AT(28, 164, "AN V210.0"); AN(B('V', 210, 0));
    PLC_AT(28, 165, "OLD"); OLD();
    PLC_AT(28, 166, "= Q0.0"); OUT('Q', 0, 0);

    /* Network 29 */
    /* Pump proof timer: pump on without proof (preset VW318) */
    PLC_AT(29, 169, "LD Q0.0"); LD(B('Q', 0, 0));
    PLC_AT(29, 170, "AN I1.3"); AN(B('I', 1, 3));
    PLC_AT(29, 171, "TON T47, VW318"); TON(47, RW('V', 318));

    /* Network 30 */
    /* Pump fault: latched when the pump has run without proof, cleared by the reset */
    PLC_AT(30, 174, "LD T47"); LD(TB(47));
    PLC_AT(30, 175, "O V210.0"); O(B('V', 210, 0));
    PLC_AT(30, 176, "AN V230.1"); AN(B('V', 230, 1));
    PLC_AT(30, 177, "= V210.0"); OUT('V', 210, 0);

    /* Network 31 */

    /* Network 32 */
    PLC_AT(32, 180, "LDB<> VB210, 0"); LDB(RB('V', 210), !=, 0);
    PLC_AT(32, 181, "= Q1.1"); OUT('Q', 1, 1);

    /* Network 33 */
    PLC_AT(33, 183, "LDB<> VB202, 16"); LDB(RB('V', 202), !=, 16);
    PLC_AT(33, 184, "= Q0.3"); OUT('Q', 0, 3);

    /* Network 34 */
    PLC_AT(34, 186, "LDB= VB202, 1"); LDB(RB('V', 202), ==, 1);
    PLC_AT(34, 187, "O Q0.1"); O(B('Q', 0, 1));
    PLC_AT(34, 188, "OB= VB202, 10"); OB(RB('V', 202), ==, 10);
    PLC_AT(34, 189, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(34, 190, "AB<> VB202, 5"); AB(RB('V', 202), !=, 5);
    PLC_AT(34, 191, "AB<> VB202, 0"); AB(RB('V', 202), !=, 0);
    PLC_AT(34, 192, "AB<> VB202, 13"); AB(RB('V', 202), !=, 13);
    PLC_AT(34, 193, "= Q0.1"); OUT('Q', 0, 1);

    /* Network 35 */
    PLC_AT(35, 195, "LDB= VB202, 4"); LDB(RB('V', 202), ==, 4);
    PLC_AT(35, 196, "O Q0.2"); O(B('Q', 0, 2));
    PLC_AT(35, 197, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(35, 198, "AB<> VB202, 0"); AB(RB('V', 202), !=, 0);
    PLC_AT(35, 199, "AB<> VB202, 11"); AB(RB('V', 202), !=, 11);
    PLC_AT(35, 200, "= Q0.2"); OUT('Q', 0, 2);

    /* Network 36 */
    PLC_AT(36, 202, "LDB= VB202, 6"); LDB(RB('V', 202), ==, 6);
    PLC_AT(36, 203, "= Q1.0"); OUT('Q', 1, 0);

    /* Network 37 */

    /* Network 38 */

    /* Network 39 */

    /* Network 40 */

    /* Network 41 */
    PLC_AT(41, 209, "LD I0.4"); LD(B('I', 0, 4));
    PLC_AT(41, 210, "EU"); EU(3);
    PLC_AT(41, 211, "= V242.4"); OUT('V', 242, 4);

    /* Network 42 */
    /* Bump request latch (not accepted during a pump fault) */
    PLC_AT(42, 214, "LD V242.4"); LD(B('V', 242, 4));
    PLC_AT(42, 215, "O Q0.4"); O(B('Q', 0, 4));
    PLC_AT(42, 216, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(42, 217, "AN V210.0"); AN(B('V', 210, 0));
    PLC_AT(42, 218, "AN V242.2"); AN(B('V', 242, 2));
    PLC_AT(42, 219, "= Q0.4"); OUT('Q', 0, 4);

    /* Network 43 */
    /* (spare: I1.1 network removed) */

    /* Network 44 */
    /* Bumps complete (status light): on when the bump count is reached, */
    /* off when back in running, or at the next Start, Bump or immediate stop */
    PLC_AT(44, 225, "LD C0"); LD(CB(0));
    PLC_AT(44, 226, "EU"); EU(4);
    PLC_AT(44, 227, "O Q0.5"); O(B('Q', 0, 5));
    PLC_AT(44, 228, "AN V230.0"); AN(B('V', 230, 0));
    PLC_AT(44, 229, "AN V242.4"); AN(B('V', 242, 4));
    PLC_AT(44, 230, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(44, 231, "AB<> VB202, 6"); AB(RB('V', 202), !=, 6);
    PLC_AT(44, 232, "= Q0.5"); OUT('Q', 0, 5);

    /* Network 45 */
    /* Return to running after a bump (V242.6 / Q0.6): set by a bump request in state 6, */
    /* cancelled by Stop (I1.2), the immediate stop (I0.2) or a pump fault (V210.0) */
    PLC_AT(45, 236, "LD V242.4"); LD(B('V', 242, 4));
    PLC_AT(45, 237, "AB= VB202, 6"); AB(RB('V', 202), ==, 6);
    PLC_AT(45, 238, "O V242.6"); O(B('V', 242, 6));
    PLC_AT(45, 239, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(45, 240, "AN I1.2"); AN(B('I', 1, 2));
    PLC_AT(45, 241, "AN V210.0"); AN(B('V', 210, 0));
    PLC_AT(45, 242, "AB<> VB202, 19"); AB(RB('V', 202), !=, 19);
    PLC_AT(45, 243, "AB<> VB202, 1"); AB(RB('V', 202), !=, 1);
    PLC_AT(45, 244, "= V242.6"); OUT('V', 242, 6);
    PLC_AT(45, 245, "= Q0.6"); OUT('Q', 0, 6);

    /* Network 46 */

    /* Network 47 */

    /* Network 48 */
    /* Number of bumps VW0 is written by the HMI (parameter 20, Revive Strokes) */

    /* Network 49 */

    /* Network 50 */

    /* Network 51 */
    /* Bump start sequence to enable process,Enable only on positive trans, stop after count has been reached */
    PLC_AT(51, 254, "LD Q0.4"); LD(B('Q', 0, 4));
    PLC_AT(51, 255, "O V242.2"); O(B('V', 242, 2));
    PLC_AT(51, 256, "AN I0.2"); AN(B('I', 0, 2));
    PLC_AT(51, 257, "AN C0"); AN(CB(0));
    PLC_AT(51, 258, "AN Q0.5"); AN(B('Q', 0, 5));
    PLC_AT(51, 259, "AB>= VB202, 16"); AB(RB('V', 202), >=, 16);
    PLC_AT(51, 260, "AB<= VB202, 17"); AB(RB('V', 202), <=, 17);
    PLC_AT(51, 261, "= V242.2"); OUT('V', 242, 2);

    /* Network 52 */
    /* Bump counter, Reset until bump process start */
    PLC_AT(52, 264, "LD T61"); LD(TB(61));
    PLC_AT(52, 265, "LDN V242.2"); LDN(B('V', 242, 2));
    PLC_AT(52, 266, "CTU C0, VW0"); CTU(0, RW('V', 0));

    /* Network 53 */
    PLC_AT(53, 268, "LD T61"); LD(TB(61));
    PLC_AT(53, 269, "ED"); ED(5);
    PLC_AT(53, 270, "= V242.1"); OUT('V', 242, 1);

    /* Network 54 */
    /* Bump off timer, either first time start or bump on timer complete (preset VW320) */
    PLC_AT(54, 273, "LD V242.2"); LD(B('V', 242, 2));
    PLC_AT(54, 274, "EU"); EU(6);
    PLC_AT(54, 275, "O V242.1"); O(B('V', 242, 1));
    PLC_AT(54, 276, "AN C0"); AN(CB(0));
    PLC_AT(54, 277, "A V242.2"); A(B('V', 242, 2));
    PLC_AT(54, 278, "TOF T60, VW320"); TOF(60, RW('V', 320));

    /* Network 55 */
    /* Bump on timer happens after bump off timer completed (preset VW322) */
    PLC_AT(55, 281, "LD T60"); LD(TB(60));
    PLC_AT(55, 282, "ED"); ED(7);
    PLC_AT(55, 283, "A V242.2"); A(B('V', 242, 2));
    PLC_AT(55, 284, "TOF T61, VW322"); TOF(61, RW('V', 322));

    /* Network 56 */
    /* bump valve control. if not in bump process or not in bump off then valve on */
    PLC_AT(56, 287, "LD V242.2"); LD(B('V', 242, 2));
    PLC_AT(56, 288, "AN T60"); AN(TB(60));
    PLC_AT(56, 289, "= V242.3"); OUT('V', 242, 3);

    /* Network 57 */
    /* Stte machine for revival cycle */
    PLC_AT(57, 292, "LDN I0.2"); LDN(B('I', 0, 2));
    PLC_AT(57, 293, "AN V204.0"); AN(B('V', 204, 0));
    PLC_AT(57, 294, "LPS"); LPS();
    PLC_AT(57, 295, "AB= VB202, 16"); AB(RB('V', 202), ==, 16);
    PLC_AT(57, 296, "A V242.3"); A(B('V', 242, 3));
    PLC_AT(57, 297, "MOVB 17, VB202"); MOVB(17, 202);
    PLC_AT(57, 298, "LRD"); LRD();
    PLC_AT(57, 299, "LDB= VB202, 15"); LDB(RB('V', 202), ==, 15);
    PLC_AT(57, 300, "LDB= VB202, 17"); LDB(RB('V', 202), ==, 17);
    PLC_AT(57, 301, "A V242.1"); A(B('V', 242, 1));
    PLC_AT(57, 302, "OLD"); OLD();
    PLC_AT(57, 303, "ALD"); ALD();
    PLC_AT(57, 304, "MOVB 16, VB202"); MOVB(16, 202);
    PLC_AT(57, 305, "LPP"); LPP();
    PLC_AT(57, 306, "LPS"); LPS();
    PLC_AT(57, 307, "AB= VB202, 18"); AB(RB('V', 202), ==, 18);
    PLC_AT(57, 308, "A Q0.6"); A(B('Q', 0, 6));
    PLC_AT(57, 309, "MOVB 19, VB202"); MOVB(19, 202);
    PLC_AT(57, 310, "LPP"); LPP();
    PLC_AT(57, 311, "AB= VB202, 17"); AB(RB('V', 202), ==, 17);
    PLC_AT(57, 312, "A C0"); A(CB(0));
    PLC_AT(57, 313, "MOVB 18, VB202"); MOVB(18, 202);
}
