#!/usr/bin/env python3
"""
Convert a STEP 7-Micro/WIN STL export (.awl) into program.c for main/plc/plc.c.

    python tools/awl_to_c.py [--plain] main/plc/filter.awl main/plc/program.c

Each instruction gets a PLC_AT(network, line, "text") in front of it, for the debugger
(breakpoints, trace, error lines). They compile to nothing when the debugger is off in
menuconfig, so normally you don't need --plain, which leaves them out.

Only the main program (ORGANIZATION_BLOCK) is converted; empty subroutines/interrupts are
ignored. Any instruction the runtime doesn't support stops the conversion with an error.
"""
import re
import sys

AREA = {'I': 'I', 'Q': 'Q', 'M': 'M', 'V': 'V', 'S': 'S', 'SM': 'X', 'AI': 'A', 'AQ': 'O'}
BIT = re.compile(r'^(SM|I|Q|M|V|S)(\d+)\.([0-7])$')
SIZED = re.compile(r'^(SM|AI|AQ|I|Q|M|V|S)(B|W|D)(\d+)$')
TMR = re.compile(r'^T(\d+)$')
CNT = re.compile(r'^C(\d+)$')
CMP = {'=': '==', '<>': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>='}


def fail(n, msg):
    sys.exit('line %d: %s' % (n, msg))


def bit_read(op, n):
    m = BIT.match(op)
    if m:
        return "B('%s', %s, %s)" % (AREA[m.group(1)], m.group(2), m.group(3))
    m = TMR.match(op)
    if m:
        return 'TB(%s)' % m.group(1)
    m = CNT.match(op)
    if m:
        return 'CB(%s)' % m.group(1)
    fail(n, "unsupported bit operand '%s'" % op)


def value(op, n):
    if re.match(r'^-?\d+$', op):
        return op
    if op.startswith('16#'):
        return str(int(op[3:], 16))
    m = SIZED.match(op)
    if m:
        size = {'B': 'RB', 'W': 'RW', 'D': 'RD'}[m.group(2)]
        return "%s('%s', %s)" % (size, AREA[m.group(1)], m.group(3))
    fail(n, "unsupported value operand '%s'" % op)


def convert(lines, debug=True):
    out, in_main, net, edges = [], False, 0, 0
    for n, raw in enumerate(lines, 1):
        line = raw.strip()
        if line.startswith('ORGANIZATION_BLOCK'):
            in_main = True
            continue
        if line.startswith('END_ORGANIZATION_BLOCK'):
            in_main = False
            continue
        if not in_main or not line or line.startswith(('TITLE', 'BEGIN')):
            continue
        if line.startswith('Network'):
            net = int(line.split()[1])
            out.append('\n    /* %s */' % line.split('//')[0].strip())
            continue
        if line.startswith('//'):
            text = line[2:].strip()
            if text:
                out.append('    /* %s */' % text.replace('*/', '* /'))
            continue

        parts = line.split(None, 1)
        ins = parts[0]
        ops = [o.strip() for o in parts[1].split(',')] if len(parts) > 1 else []

        if ins in ('LD', 'LDN', 'A', 'AN', 'O', 'ON'):
            c = '%s(%s);' % (ins, bit_read(ops[0], n))
        elif ins in ('NOT', 'ALD', 'OLD', 'LPS', 'LRD', 'LPP'):
            c = '%s();' % ins
        elif ins in ('EU', 'ED'):
            c = '%s(%d);' % (ins, edges)          # each EU/ED has its own edge memory
            edges += 1
        elif ins == '=':
            m = BIT.match(ops[0])
            if not m:
                fail(n, "'=' needs a bit operand")
            c = "OUT('%s', %s, %s);" % (AREA[m.group(1)], m.group(2), m.group(3))
        elif re.match(r'^(LDB|AB|OB|LDW|AW|OW)(=|<>|<=|>=|<|>)$', ins):
            m = re.match(r'^(LDB|AB|OB|LDW|AW|OW)(.+)$', ins)
            c = '%s(%s, %s, %s);' % (m.group(1), value(ops[0], n), CMP[m.group(2)], value(ops[1], n))
        elif ins in ('MOVB', 'MOVW'):
            d = re.match(r'^V%s(\d+)$' % ins[3], ops[1])
            if not d:
                fail(n, '%s destination must be V%s' % (ins, ins[3]))
            c = '%s(%s, %s);' % (ins, value(ops[0], n), d.group(1))
        elif ins in ('TON', 'TOF'):
            t = TMR.match(ops[0])
            c = '%s(%s, %s);' % (ins, t.group(1), value(ops[1], n))
        elif ins == 'CTU':
            k = CNT.match(ops[0])
            c = 'CTU(%s, %s);' % (k.group(1), value(ops[1], n))
        else:
            fail(n, "instruction '%s' is not supported by the runtime" % ins)

        stl = ' '.join(line.split()).replace('\\', '\\\\').replace('"', '\\"')
        if debug:
            out.append('    PLC_AT(%d, %d, "%s"); %s' % (net, n, stl, c))
        else:
            out.append('    %-34s /* %s */' % (c, line))
    if edges > 256:
        sys.exit('too many EU/ED instructions (%d, the runtime has 256)' % edges)
    return out


def main():
    plain = '--plain' in sys.argv[1:]
    args = [a for a in sys.argv[1:] if a != '--plain']
    if len(args) != 2:
        sys.exit(__doc__)
    with open(args[0], encoding='latin-1') as f:
        body = convert(f.read().splitlines(), debug=not plain)
    name = args[0].replace('\\', '/').split('/')[-1]
    with open(args[1], 'w') as f:
        f.write('/* Generated by tools/awl_to_c.py from %s - do not edit, edit the .awl */\n' % name)
        f.write('#include "plc.h"\n\nconst char *const plc_program_file = "%s";\n\nvoid plc_main(void)\n{' % name)
        f.write('\n'.join(body))
        f.write('\n}\n')


if __name__ == '__main__':
    main()
