#!/usr/bin/env python3
"""
Convert a PNG (transparency supported) into an LVGL 9 image the firmware can show.

    pip install pillow
    python tools/png_to_lvgl.py  aquarevival.png  logo_aquarevival  --max-width 600
    python tools/png_to_lvgl.py  kalamazoo.png    logo_customer     --max-width 500

Writes main/ui/logos/<name>.c and <name>.h. The splash screen picks them up automatically
on the next build (no other edits needed). Use exactly these two names:
    logo_aquarevival  - first splash screen
    logo_customer     - customer logo shown after the bubbles
"""
import argparse
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "..", "main", "ui", "logos")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("png")
    ap.add_argument("name", help="C symbol name, e.g. logo_aquarevival")
    ap.add_argument("--max-width", type=int, default=700)
    ap.add_argument("--max-height", type=int, default=400)
    ap.add_argument("--scale", type=float, default=0, help="resize by this factor instead (e.g. 1.8)")
    ap.add_argument("--key-color", default="", help="make this background colour transparent, e.g. 144D81")
    ap.add_argument("--format", choices=["argb8888", "rgb565"], default="argb8888",
                    help="rgb565 = half the flash, no transparency (good for photos)")
    ap.add_argument("--out-dir", default=OUT_DIR, help="where to write the .c/.h")
    a = ap.parse_args()

    img = Image.open(a.png).convert("RGBA")
    if a.key_color:                             # background colour -> transparent
        kr, kg, kb = (int(a.key_color[i:i + 2], 16) for i in (0, 2, 4))
        px = img.load()
        for yy in range(img.height):
            for xx in range(img.width):
                r, g, b, _ = px[xx, yy]
                if (r, g, b) == (kr, kg, kb):
                    px[xx, yy] = (r, g, b, 0)
    if a.scale > 0:
        img = img.resize((round(img.width * a.scale), round(img.height * a.scale)), Image.LANCZOS)
    else:
        img.thumbnail((a.max_width, a.max_height), Image.LANCZOS)
    w, h = img.size

    if a.format == "rgb565":
        rgb = img.convert("RGB").tobytes()
        data = bytearray()
        for i in range(0, len(rgb), 3):
            v = ((rgb[i] >> 3) << 11) | ((rgb[i + 1] >> 2) << 5) | (rgb[i + 2] >> 3)
            data += bytes((v & 0xFF, v >> 8))            # little-endian uint16
        cf, bpp = "LV_COLOR_FORMAT_RGB565", 2
    else:
        data = bytearray(img.tobytes())            # R, G, B, A ...
        data[0::4], data[2::4] = data[2::4], data[0::4]   # LVGL ARGB8888 byte order: B, G, R, A
        cf, bpp = "LV_COLOR_FORMAT_ARGB8888", 4

    os.makedirs(a.out_dir, exist_ok=True)
    c_path = os.path.join(a.out_dir, a.name + ".c")
    h_path = os.path.join(a.out_dir, a.name + ".h")

    with open(c_path, "w") as f:
        f.write('/* Generated by tools/png_to_lvgl.py from %s */\n' % os.path.basename(a.png))
        f.write('#include "lvgl.h"\n\n')
        # Must be word-aligned: LVGL reads ARGB8888 pixels 4 bytes at a time and the ESP32-S3
        # faults (LoadStoreAlignment) on a misaligned read.
        f.write('static const uint8_t %s_map[] __attribute__((aligned(4))) = {\n' % a.name)
        for i in range(0, len(data), 24):
            f.write("    " + ", ".join("0x%02x" % v for v in data[i:i + 24]) + ",\n")
        f.write("};\n\n")
        f.write("const lv_image_dsc_t %s = {\n" % a.name)
        f.write("    .header.magic  = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("    .header.cf     = %s,\n" % cf)
        f.write("    .header.w      = %d,\n" % w)
        f.write("    .header.h      = %d,\n" % h)
        f.write("    .header.stride = %d,\n" % (w * bpp))
        f.write("    .data_size     = sizeof(%s_map),\n" % a.name)
        f.write("    .data          = %s_map,\n" % a.name)
        f.write("};\n")

    with open(h_path, "w") as f:
        f.write("#pragma once\n#include \"lvgl.h\"\n")
        f.write("extern const lv_image_dsc_t %s;\n" % a.name)

    print("Wrote %s (%dx%d, %d KB)" % (c_path, w, h, len(data) // 1024))


if __name__ == "__main__":
    main()
